apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-app
  template:
    metadata:
      labels:
        app: azure-app
    spec:
      containers:
      - name: azure-app
        image: itech0306/azure-devops-app:$(Build.BuildId)
        ports:
        - containerPort: 80
